---
title: "MTC Weighted 2023 Travel Diary Survey Review"
output:
  word_document:
    toc: true
  html_document:
    theme: cosmo
    toc: true
---

```{r setup, include=FALSE}
# Load necessary packages
library(tidyverse)
library(tidycensus)
library(survey)

# Load the data
folder  <- "M:/Data/HomeInterview/Bay Area Travel Study 2023/Data/Full Weighted 2023 Dataset/WeightedDataset_08092024"
day     <- read.csv(file.path(folder,"day.csv"))
hh      <- read.csv(file.path(folder,"hh.csv"))
person  <- read.csv(file.path(folder,"person.csv"))
trip    <- read.csv(file.path(folder,"trip.csv"))
vehicle <- read.csv(file.path(folder,"person.csv"))

```

# Households by County (Total)

```{r hhs_total, echo=FALSE}

household <- hh %>% 
  mutate(home_county = recode(home_county,
    "6001" = "Alameda",
    "6013" = "Contra Costa",
    "6041" = "Marin",
    "6055" = "Napa",
    "6075" = "San Francisco",
    "6081" = "San Mateo",
    "6085" = "Santa Clara",
    "6095" = "Solano",
    "6097" = "Sonoma"))

#table(household$home_county)
#survey_design <- svydesign(ids = ~1, data = household, weights = ~hh_weight)
#weighted_freq <- svytable(~home_county, survey_design)
#print(weighted_freq)

household_county_bats <- household %>% 
  group_by(home_county) %>% 
  summarize(Total_BATS=round(sum(hh_weight)),rMove_BATS=round(sum(hh_weight_rmove_only))) %>% 
  ungroup() %>% 
  rename(County=home_county)

hh_marin_napa_sonoma_bats <- household %>% 
  filter(home_county %in% c("Marin","Napa","Sonoma")) %>% 
  summarize(Total_BATS=round(sum(hh_weight)),rMove_BATS=round(sum(hh_weight_rmove_only))) %>% 
  mutate(home_county="Marin_Napa_Sonoma") %>% 
  rename(County=home_county) 

household_region_bats <- household %>% 
  summarize(Total_BATS=round(sum(hh_weight)),rMove_BATS=round(sum(hh_weight_rmove_only))) %>% 
  mutate(home_county="Bay Area") %>% 
  rename(County=home_county) %>% 
    rbind(household_county_bats,hh_marin_napa_sonoma_bats,.)

household_county_acs <- get_acs(
  geography = "county",
  county = c("Alameda","Contra Costa","Marin","Napa","San Francisco","San Mateo","Santa Clara","Solano","Sonoma"),
  state = "california",
  variables = "B08201_001",
  year = 2022,
  survey = "acs1") %>% 
  rename(County=NAME) %>% 
   mutate(County = gsub(" County, California", "", County)) %>% 
  select(County,Total_ACS=estimate)

hh_marin_napa_sonoma_acs <- household_county_acs %>% 
  filter(County %in% c("Marin","Napa","Sonoma")) %>% 
  summarize(Total_ACS=sum(Total_ACS)) %>% 
  mutate(County="Marin_Napa_Sonoma") 

household_region_acs <- household_county_acs %>% 
  summarize(Total_ACS=sum(Total_ACS)) %>% 
  mutate(County="Bay Area") %>% 
  rbind(household_county_acs,hh_marin_napa_sonoma_acs,.)

household_comparison <- left_join(household_region_bats,household_region_acs,by="County") %>% 
  mutate(BATS_ACS_Diff=round(((Total_BATS/Total_ACS)-1)*100),rMove_ACS_Diff=round(((rMove_BATS/Total_ACS)-1)*100))

household_comparison_total <- household_comparison %>% select(County,Total_BATS,Total_ACS,BATS_ACS_Diff)
household_comparison_rmove <- household_comparison %>% select(County,rMove_BATS,Total_ACS,rMove_ACS_Diff)

household_comparison_total

```

# Households by County (rMove Only)

```{r hhs_county, echo=FALSE}
household_comparison_rmove
```

# Population by County (Total)

```{r pop_county_tot, echo=FALSE}

household_joiner <- household %>% 
  select(hh_id,home_county)

person_county_bats <- person %>%
  left_join(.,household_joiner,by="hh_id") %>% 
  group_by(home_county) %>% 
  summarize(Total_BATS=round(sum(person_weight)),rMove_BATS=round(sum(person_weight_rmove_only))) %>% 
  ungroup() %>% 
  rename(County=home_county)

person_marin_napa_sonoma_bats <- person %>% 
  left_join(.,household_joiner,by="hh_id") %>% 
  filter(home_county %in% c("Marin","Napa","Sonoma")) %>% 
  summarize(Total_BATS=round(sum(person_weight)),rMove_BATS=round(sum(person_weight_rmove_only))) %>% 
  ungroup() %>% 
  mutate(County="Marin_Napa_Sonoma")

person_region_bats <- person %>% 
  left_join(.,household_joiner,by="hh_id") %>% 
  summarize(Total_BATS=round(sum(person_weight)),rMove_BATS=round(sum(person_weight_rmove_only))) %>% 
  mutate(home_county="Bay Area") %>% 
  rename(County=home_county) %>% 
    rbind(person_county_bats,person_marin_napa_sonoma_bats,.)

person_county_acs <- get_acs(
  geography = "county",
  county = c("Alameda","Contra Costa","Marin","Napa","San Francisco","San Mateo","Santa Clara","Solano","Sonoma"),
  state = "california",
  variables = "B01001_001",
  year = 2022,
  survey = "acs1") %>% 
  rename(County=NAME) %>% 
   mutate(County = gsub(" County, California", "", County)) %>% 
  select(County,Total_ACS=estimate)

person_marin_napa_sonoma_acs <- person_county_acs %>% 
  filter(County %in% c("Marin","Napa","Sonoma")) %>% 
  summarize(Total_ACS=sum(Total_ACS)) %>% 
  mutate(County="Marin_Napa_Sonoma") 

person_region_acs <- person_county_acs %>% 
  summarize(Total_ACS=sum(Total_ACS)) %>% 
  mutate(County="Bay Area") %>% 
  rbind(person_county_acs,person_marin_napa_sonoma_acs,.)

person_comparison <- left_join(person_region_bats,person_region_acs,by="County") %>% 
  mutate(BATS_ACS_Diff=round(((Total_BATS/Total_ACS)-1)*100),rMove_ACS_Diff=round(((rMove_BATS/Total_ACS)-1)*100))


person_comparison_total <- person_comparison %>% select(County,Total_BATS,Total_ACS,BATS_ACS_Diff)
person_comparison_rmove <- person_comparison %>% select(County,rMove_BATS,Total_ACS,rMove_ACS_Diff)

person_comparison_total

```

# Population by County (rMove Only)

```{r pop_county_rmove, echo=FALSE}
person_comparison_rmove
```


# Range of HH Weights by Income Category (Total)

```{r inc_weights_tot, echo=FALSE}

# Define custom order

custom_inc_order <- c("Under $25,000", "$25,000-$49,999", "$50,000-$74,999",   
"$75,000-$99,999","$100,000-$199,999", "$200,000 or more")

# Evaluate weights by household income

income_range_total <- household %>% 
  group_by(income_imputed) %>% 
  summarize(min_tot=round(min(hh_weight)),
            pct25_tot=round(quantile(hh_weight,0.25)),med_tot=round(quantile(hh_weight,0.5)),
            pct75_tot=round(quantile(hh_weight,0.75)),
            max_tot=round(max(hh_weight))) %>% 
  arrange(factor(income_imputed,levels = custom_inc_order)) %>% 
  ungroup()

income_range_total

```

# Range of HH Weights by Income Category (rMove)

```{r inc_weights_rmove, echo=FALSE}

# Evaluate rMove weights by household income

income_range_rmove <- household %>% 
  filter(hh_weight_rmove_only>0) %>% 
  group_by(income_imputed) %>% 
  summarize(min_rmov=round(min(hh_weight_rmove_only)),
            pct25_rmov=round(quantile(hh_weight_rmove_only,0.25)),
            med_rmov=round(quantile(hh_weight_rmove_only,0.5)),
            pct75_rmov=round(quantile(hh_weight_rmove_only,0.75)),
            max_rmov=round(max(hh_weight_rmove_only)))  %>% 
  arrange(factor(income_imputed,levels = custom_inc_order)) %>% 
  ungroup()

income_range_rmove

```


# Range of Person Weights by Race/Ethnicity (Total)

```{r race_weights_total, echo=FALSE}

custom_race_order <- c("white","black","asian_pacific","other","hispanic")

race_recoded_total <- person %>% 
  filter(relationship !=6) %>% 
  mutate(race_recoded_total=if_else(ethnicity_imputed=="hispanic","hispanic",race_imputed),
         race_recoded_total=recode(race_recoded_total,"afam"="black")) %>% 
  group_by(race_recoded_total) %>% 
    summarize(min_tot=round(min(person_weight)),pct25_total=round(quantile(person_weight,0.25)),
              med_tot=round(quantile(person_weight,0.5)), pct75_tot=round(quantile(person_weight,0.75)),
              max_tot=round(max(person_weight))) %>% 
  arrange(factor(race_recoded_total,levels = custom_race_order))

race_recoded_total

```

# Range of Person Weights by Race/Ethnicity (rMove)

```{r race_weights_rmove, echo=FALSE}

race_recoded_rmove <- person %>% 
  filter(relationship !=6,person_weight_rmove_only>0) %>% 
  mutate(race_recoded_rmove=if_else(ethnicity_imputed_rmove_only=="hispanic","hispanic",race_imputed_rmove_only),
         race_recoded_rmove=recode(race_recoded_rmove,"afam"="black")) %>% 
  group_by(race_recoded_rmove) %>% 
    summarize(min_rmov=round(min(person_weight_rmove_only)),
              pct25_rmov=round(quantile(person_weight_rmove_only,0.25)),
              med_rmov=round(quantile(person_weight_rmove_only,0.5)),
              pct75_rmov=round(quantile(person_weight_rmove_only,0.75)),
              max_rmov=round(max(person_weight_rmove_only))) %>% 
  arrange(factor(race_recoded_rmove,levels = custom_race_order))

race_recoded_rmove
    
```  




